server:
    port: 8082


spring:
  profiles:
    active: qa

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: u$erloc@lh0st
  jpa:
    hibernate:
      ddL-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to this tutorial!!


management:
  endpoints:
    web:
      exposure:
        include: "*"


---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    password: u$erloc@lh0st
  jpa:
    hibernate:
      ddL-auto: create
    show-sql: 'true'
welcome:
  message: Welcome to this tutorial!!


management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"


---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    password: u$erloc@lh0st
  jpa:
    hibernate:
      ddL-auto: create
    show-sql: 'true'
welcome:
  message: Welcome to this tutorial!!